### ISSUE TITLE
Erreur d'installation de waterline/modelling

### ISSUE THREAD

**Issue by lhadjadj** [france-connect/identity-providers-examples#1]
Bonjour, lors de l'installation : npm install, le message d'erreur apparaît : 

npm http GET https://registry.npmjs.org/modelling
npm http 304 https://registry.npmjs.org/modelling
npm ERR! git clone git://github.com/balderdashy/waterline Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-balderdashy-waterline-ef730cd2'
npm ERR! git clone git://github.com/balderdashy/waterline fatal: unable to connect to github.com:
npm ERR! git clone git://github.com/balderdashy/waterline github.com: Nom ou service inconnu
npm ERR! Error: Command failed: Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-balderdashy-waterline-ef730cd2'
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com: Nom ou service inconnu
npm ERR!
npm ERR!
npm ERR!     at ChildProcess.exithandler (child_process.js:647:15)
npm ERR!     at ChildProcess.EventEmitter.emit (events.js:98:17)
npm ERR!     at maybeClose (child_process.js:753:16)
npm ERR!     at Process.ChildProcess._handle.onexit (child_process.js:820:5)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.16.0-4-686-pae
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! cwd /opt/DATA/OPENID-PROV/identity-providers-examples/OpenID-Connect-NodeJS
npm ERR! node -v v0.10.28
npm ERR! npm -v 1.4.9
npm ERR! code 128
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/DATA/OPENID-PROV/identity-providers-examples/OpenID-Connect-NodeJS/npm-debug.log
npm ERR! not ok code 0

L'installation manuelle (clone + npm install) de waterline fonctionne par ailleurs.

Avez-vous une idée ?

Merci d'avance.

**Comment by fpetitit** [comment]
Bonjour,
d'après la stacktrace, il semble que votre client Git n'arrive pas à atteindre le site github.com : 
> npm ERR! git clone git://github.com/balderdashy/waterline fatal: unable to connect to github.com:
> npm ERR! git clone git://github.com/balderdashy/waterline github.com: Nom ou service inconnu
> npm ERR! Error: Command failed: Clonage dans le dépôt nu '/root/.npm/_git-remotes/git-github-com-balderdashy-waterline-ef730cd2'
> npm ERR! fatal: unable to connect to github.com:
> npm ERR! github.com: Nom ou service inconnu

Ne seriez-vous pas derrière un proxy d'entreprise ? L'avez-vous bien configuré dans votre client Git ?

**Comment by lhadjadj** [comment]
Bonjour, oui je suis derrière un proxy j'ai ajouté les variables : 

git config --global http.proxy http://192.168.x.x:8080
git config --global https.proxy http://192.168.x.x:8080
npm config set proxy http://192.168.x.x:8080
npm config set https-proxy http://192.168.x.x:8080

et aussi : http_proxy=http://192.168.x.x8080

J'arrive à cloner en https mais pas en git.

**Comment by fpetitit** [comment]
OK
C'est peut-être le protocole 'git://' qui est bloqué par votre proxy, alors que quand vous faites du git sur des url HTTP/S cela fonctionne.
Cette page donne des infos pour contourner ce problème : 
http://stackoverflow.com/questions/14937405/npm-git-protocol-dependencies

**Comment by lhadjadj** [comment]
Merci, cela fonctionne, je vais pourvoir reprendre les tests.
Chapo :+1:
